export const MemStore =  [
    {
        title:"Cat",
        upvotes:2,
        downvotes:0,
        favourite: false,
        img:"/Assets/img/image1.png",
    },
    {
        title:"Giraffe",
        upvotes:4,
        downvotes:5,
        favourite: true,
        img:"/Assets/img/image2.png",
    },
    {
        title:"Squirrel",
        upvotes:3,
        downvotes:0,
        favourite: false,
        img:"/Assets/img/image3.png",
    },
    {
        title:"Panda",
        upvotes:8,
        downvotes:0,
        favourite: true,
        img:"/Assets/img/image4.png",
       
    },
    {
        title:"Dog",
        upvotes:5,
        downvotes:0,
        favourite: false,
        img:"/Assets/img/image5.png",
    },
    {
        title:"Turtle",
        upvotes:6,
        downvotes:0,
        favourite: false,
        img:"/Assets/img/image6.png",
    },
    {
        title:"Carpet cat",
        upvotes:7,
        downvotes:0,
        favourite: true,
        img:"/Assets/img/image7.png",
    },
    {
        title:"Hedgehog",
        upvotes:2,
        downvotes:0,
        favourite: false,
        img:"/Assets/img/image8.png",
    },
    {
        title:"Fox",
        upvotes:0,
        downvotes:1,
        favourite: false,
        img:"/Assets/img/image9.png",
    },
    {
        title:"Sweet cat",
        upvotes:7,
        downvotes:0,
        favourite: true,
        img:"/Assets/img/image10.png",
    },
];